import { Outfit, Urbanist } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

const urbanist = Urbanist({
	variable: "--font-urbanist",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ViewTransitions>
			<html lang="en">
				<body
					className={`${outfit.variable} ${urbanist.variable} antialiased`}
				>
					<Header />
					<main className="relative z-10 bg-white">{children}</main>
					<Footer />
				</body>
			</html>
		</ViewTransitions>
	);
}
