import { headers } from "next/headers";
import { Outfit, Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const outfit = Outfit({
	variable: "--font-outfit",
	subsets: ["latin"],
});

const urbanist = Urbanist({
	variable: "--font-urbanist",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	const pathname = headers().get("x-pathname") || "/";
	const isHome = pathname === "/";

	return (
		<html lang="en">
			<body
				className={`${outfit.variable} ${urbanist.variable} antialiased`}
			>
				<Header />
				<main className={isHome ? "" : "mt-24"}>{children}</main>
			</body>
		</html>
	);
}
